import 'package:apkdemo/constans.dart';
import 'regis.dart';
import 'regis3.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class Regis2Page extends StatefulWidget {
  @override
  _Regis2PageState createState() => _Regis2PageState();
}

class _Regis2PageState extends State<Regis2Page> {
  String selectedCountry = 'Select Country';
  String selectedProvince = 'Select Province';
  String selectedCity = 'Select City';
  String selectedJob = 'Select Job Type';
  String selectedOfficer = 'Select Branch Officer';
  @override
  Widget build(BuildContext context) {
    List<String> country = ['Select Country', 'Indonesia'];
    List<String> job = [
      'Select job',
      'Pekerja Swasta',
      'Pekerja Negeri',
      'Wiraswasta',
      'Pelajar/Mahasiswa',
      'Petani',
      'Nelayan',
      'Karyawan',
      'Tenaga Kesehatan',
      'Tenaga Pendidikan',
      'Buruh',
      'Pensiunan',
      'Tidak Bekerja'
    ];
    List<String> officer = [
      'Select Branch Officer',
      'Sekretariat Pusat',
      'Chapter Bandung',
      'Chapter Jakarta',
      'Chapter Cirebon',
      'Chapter Yogyakarta',
      'Chapter Banten',
      'Chapter Makasar',
      'Chapter Semarang',
      'Chapter Bali',
      'Chapter Subang',
      'Chapter Soppeng',
      'Chapter Takalar',
      ''
    ];
    List<String> province = [
      'Select Province',
      'Aceh',
      'Sumatera Utara',
      'Sumatera Barat',
      'Riau',
      'Jambi',
      'Sumatera Selatan',
      'Bengkulu',
      'Lampung',
      'Kep. Bangka Belitung',
      'Kep. Riau',
      'DKI. Jakarta',
      'Jawa Barat',
      'Jawa Tengah',
      'DI. Yogyakarta',
      'Jawa Timur',
      'Banten',
      'Bali',
      'Nusa Tenggara Barat',
      'Nusa Tenggara Timur',
      'Kalimantan Barat',
      'Kalimantan Tengah',
      'Kalimantan Selatan',
      'Kalimantan Timur',
      'Kalimantan Utara',
      'Sulawesi Utara',
      'Sulawesi Tengah',
      'Sulawesi Selatan',
      'Sulawesi Tenggara',
      'Gorontalo',
      'Sulawesi Barat',
      'Maluku',
      'Maluku Utara',
      'Papua',
      'Papua Barat'
    ];
    List<String> city = [
      'Select City',
      'Kab. Aceh Selatan',
      'Kab. Aceh Tenggara',
      'Kab. Aceh Timur',
      'Kab. Aceh Tengah',
      'Kab. Aceh Barat',
      'Kab. Aceh Besar',
      'Kab. Pidie',
      'Kab. Aceh Utara',
      'Kab. Simeulue',
      'Kab. Aceh Singkil',
      'Kab. Bireuen',
      'Kab. Aceh Barat Daya',
      'Kab. Gayo Lues',
      'Kab. Aceh Jaya',
      'Kab. Nagan Raya',
      'Kab. Aceh Tamiang',
      'Kab. Bener Meriah',
      'Kab. Pidie Jaya',
      'Kota Banda Aceh',
      'Kota Sabang',
      'Kota Lhokseumawe',
      'Kota Langsa',
      'Kota Subulussalam',
      'Kab. Tapanuli Tengah',
      'Kab. Tapanuli Utara',
      'Kab. Tapanuli Selatan',
      'Kab. Nias',
      'Kab. Langkat',
      'Kab. Karo',
      'Kab. Deli Serdang',
      'Kab. Simalungun',
      'Kab. Asahan',
      'Kab. Labuhanbatu',
      'Kab. Dairi',
      'Kab. Toba Samosir',
      'Kab. Mandailing Natal',
      'Kab. Nias Selatan',
      'Kab. Pakpak Bharata',
      'Kab. Humbang Hasundutan',
      'Kab. Samosir',
      'Kab. Serdang Bedagai',
      'Kab. Batu Bara',
      'Kab. Padang Lawas Utara',
      'Kab. Padang Lawas',
      'Kab. Labuhanbatu Selatan',
      'Kab. Labuhanbatu Utara',
      'Kab. Nias Utara',
      'Kab. Nias Barat',
      'Kota Medan',
      'Kota Pematang Siantar',
      'Kota Sibolga',
      'Kota Tanjung Balai',
      'Kota Binjai',
      'Kota Tebing Tinggi',
      'Kota Padang Sidempuan',
      'Kota Gunungsitoli',
      'Kab. Pesisir Selatan',
      'Kab. Solok',
      'Kab. Sijunjung',
      'Kab. Tanah Datar',
      'Kab. Padang Pariaman',
      'Kab. Agam',
      'Kab. Lima Puluh Kota',
      'Kab. Pasaman',
      'Kab. Kepulauan Mentawai',
      'Kab. Dharmasraya',
      'Kab. Solok Selatan',
      'Kab. Pasaman Barat',
      'Kota Padang',
      'Kota Solok',
      'Kota Sawahlunto',
      'Kota Padang Panjang',
      'Kota Bukittinggi',
      'Kota Payakumbuh',
      'Kota Pariaman',
      'Kab. Kampar',
      'Kab. Indragiri Hulu',
      'Kab. Bengkalis',
      'Kab. Indragiri Hilir',
      'Kab. Pelalawan',
      'Kab. Rokan Hulu',
      'Kab. Rokan Hilir',
      'Kab. Siak',
      'Kab. Kuantan Singingi',
      'Kab. Kepulauan Meranti',
      'Kota Pekanbaru',
      'Kota Dumai',
      'Kab. Kerinci',
      'Kab. Merangin',
      'Kab. Sarolangun',
      'Kab. Batanghari',
      'Kab. Muaro Jambi',
      'Kab. Tanjung Jabung Barat',
      'Kab. Tanjung Jabung Timur',
      'Kab. Bungo',
      'Kab. Tebo',
      'Kota Jambi',
      'Kota Sungai Penuh',
      'Kab. Ogan Komering Ulu',
      'Kab. Ogan Komering Ilir',
      'Kab. Muara Enim',
      'Kab. Lahat',
      'Kab. Musi Rawas',
      'Kab. Musi Banyuasin',
      'Kab. Banyuasin',
      'Kab. Ogan Komering Ulu Timur',
      'Kab. Ogan Komering Ulu Selatan',
      'Kab. Ogan Ilir',
      'Kab. Empat Lawang',
      'Kab. Penukal Abab Lematang Ilir',
      'Kab. Musi Rawas Utara',
      'Kota Palembang',
      'Kota Pagar Alam',
      'Kota Lubuk Linggau',
      'Kota Prabumulih',
      'Kab. Bengkulu Selatan',
      'Kab. Rejang Lebong',
      'Kab. Bengkulu Utara',
      'Kab. Kaur',
      'Kab. Seluma',
      'Kab. Muko Muko',
      'Kab. Lebong',
      'Kab. Kepahiang',
      'Kab. Bengkulu Tengah',
      'Kota Bengkulu',
      'Kab. Lampung Selatan',
      'Kab. Lampung Tengah',
      'Kab. Lampung Utara',
      'Kab. Lampung Barat',
      'Kab. Tulang Bawang',
      'Kab. Tanggamus',
      'Kab. Lampung Timur',
      'Kab. Way Kanan',
      'Kab. Pesawaran',
      'Kab. Pringsewu',
      'Kab. Mesuji',
      'Kab. Tulang Bawang Barat',
      'Kab. Pesisir Barat',
      'Kota Bandar Lampung',
      'Kota Metro',
      'Kab. Bangka',
      'Kab. Belitung',
      'Kab. Bangka Selatan',
      'Kab. Bangka Tengah',
      'Kab. Bangka Barat',
      'Kab. Belitung Timur',
      'Kota Pangkal Pinang',
      'Kab. Bintan',
      'Kab. Karimun',
      'Kab. Natuna',
      'Kab. Lingga',
      'Kab. Kepulauan Anambas',
      'Kota Batam',
      'Kota Tanjung Pinang',
      'Kab. Adm. Kep. Seribu',
      'Kota Adm. Jakarta Pusat',
      'Kota Adm. Jakarta Utara',
      'Kota Adm. Jakarta Barat',
      'Kota Adm. Jakarta Selatan',
      'Kota Adm. Jakarta Timur',
      'Kab. Bogor',
      'Kab. Sukabumi',
      'Kab. Cianjur',
      'Kab. Bandung',
      'Kab. Garut',
      'Kab. Tasikmalaya',
      'Kab. Ciamis',
      'Kab. Kuningan',
      'Kab. Cirebon',
      'Kab. Majalengka',
      'Kab. Sumedang',
      'Kab. Indramayu',
      'Kab. Subang',
      'Kab. Purwakarta',
      'Kab. Karawang',
      'Kab. Bekasi',
      'Kab. Bandung Barat',
      'Kab. Pangandaran',
      'Kota Bogor',
      'Kota Sukabumi',
      'Kota Bandung',
      'Kota Cirebon',
      'Kota Bekasi',
      'Kota Depok',
      'Kota Cimahi',
      'Kota Tasikmalaya',
      'Kota Banjar',
      'Kab. Cilacap',
      'Kab. Banyumas',
      'Kab. Purbalingga',
      'Kab. Banjarnegara',
      'Kab. Kebumen',
      'Kab. Purworejo',
      'Kab. Wonosobo',
      'Kab. Magelang',
      'Kab. Boyolali',
      'Kab. Klaten',
      'Kab. Sukoharjo',
      'Kab. Wonogiri',
      'Kab. Karanganyar',
      'Kab. Sragen',
      'Kab. Grobogan',
      'Kab. Blora',
      'Kab. Rembang',
      'Kab. Pati',
      'Kab. Kudus',
      'Kab. Jepara',
      'Kab. Demak',
      'Kab. Semarang',
      'Kab. Temanggung',
      'Kab. Kendal',
      'Kab. Batang',
      'Kab. Pekalongan',
      'Kab. Pemalang',
      'Kab. Tegal',
      'Kab. Brebes',
      'Kota Magelang',
      'Kota Surakarta',
      'Kota Salatiga',
      'Kota Semarang',
      'Kota Pekalongan',
      'Kota Tegal',
      'Kab. Kulon Progo',
      'Kab. Bantul',
      'Kab. Gunungkidul',
      'Kab. Sleman',
      'Kota Yogyakarta',
      'Kab. Pacitan',
      'Kab. Ponorogo',
      'Kab. Trenggalek',
      'Kab. Tulungagung',
      'Kab. Blitar',
      'Kab. Kediri',
      'Kab. Malang',
      'Kab. Lumajang',
      'Kab. Jember',
      'Kab. Banyuwangi',
      'Kab. Bondowoso',
      'Kab. Situbondo',
      'Kab. Probolinggo',
      'Kab. Pasuruan',
      'Kab. Sidoarjo',
      'Kab. Mojokerto',
      'Kab. Jombang',
      'Kab. Nganjuk',
      'Kab. Madiun',
      'Kab. Magetan',
      'Kab. Ngawi',
      'Kab. Bojonegoro',
      'Kab. Tuban',
      'Kab. Lamongan',
      'Kab. Gresik',
      'Kab. Bangkalan',
      'Kab. Sampang',
      'Kab. Pamekasan',
      'Kab. Sumenep',
      'Kota Kediri',
      'Kota Blitar',
      'Kota Malang',
      'Kota Probolinggo',
      'Kota Pasuruan',
      'Kota Mojokerto',
      'Kota Madiun',
      'Kota Surabaya',
      'Kota Batu',
      'Kab. Pandeglang',
      'Kab. Lebak',
      'Kab. Tangerang',
      'Kab. Serang',
      'Kota Tangerang',
      'Kota Cilegon',
      'Kota Serang',
      'Kota Tangerang Selatan',
      'Kab. Jembrana',
      'Kab. Tabanan',
      'Kab. Badung',
      'Kab. Gianyar',
      'Kab. Klungkung',
      'Kab. Bangli',
      'Kab. Karangasem',
      'Kab. Buleleng',
      'Kota Denpasar',
      'Kab. Lombok Barat',
      'Kab. Lombok Tengah',
      'Kab. Lombok Timur',
      'Kab. Sumbawa',
      'Kab. Dompu',
      'Kab. Bima',
      'Kab. Sumbawa Barat',
      'Kab. Lombok Utara',
      'Kota Mataram',
      'Kota Bima',
      'Kab. Kupang',
      'Kab Timor Tengah Selatan',
      'Kab. Timor Tengah Utara',
      'Kab. Belu',
      'Kab. Alor',
      'Kab. Flores Timur',
      'Kab. Sikka',
      'Kab. Ende',
      'Kab. Ngada',
      'Kab. Manggarai',
      'Kab. Sumba Timur',
      'Kab. Sumba Barat',
      'Kab. Lembata',
      'Kab. Rote Ndao',
      'Kab. Manggarai Barat',
      'Kab. Nagekeo',
      'Kab. Sumba Tengah',
      'Kab. Sumba Barat Daya',
      'Kab. Manggarai Timur',
      'Kab. Sabu Raijua',
      'Kab. Malaka',
      'Kota Kupang',
      'Kab. Sambas',
      'Kab. Mempawah',
      'Kab. Sanggau',
      'Kab. Ketapang',
      'Kab. Sintang',
      'Kab. Kapuas Hulu',
      'Kab. Bengkayang',
      'Kab. Landak',
      'Kab. Sekadau',
      'Kab. Melawi',
      'Kab. Kayong Utara',
      'Kab. Kubu Raya',
      'Kota Pontianak',
      'Kota Singkawang',
      'Kab. Kotawaringin Barat',
      'Kab. Kotawaringin Timur',
      'Kab. Kapuas',
      'Kab. Barito Selatan',
      'Kab. Barito Utara',
      'Kab. Katingan',
      'Kab. Seruyan',
      'Kab. Sukamara',
      'Kab. Lamandau',
      'Kab. Gunung Mas',
      'Kab. Pulang Pisau',
      'Kab. Murung Raya',
      'Kab. Barito Timur',
      'Kota Palangkaraya',
      'Kab. Tanah Laut',
      'Kab. Kotabaru',
      'Kab. Banjar',
      'Kab. Barito Kuala',
      'Kab. Tapin',
      'Kab. Hulu Sungai Selatan',
      'Kab. Hulu Sungai Tengah',
      'Kab. Hulu Sungai Utara',
      'Kab. Tabalong',
      'Kab. Tanah Bumbu',
      'Kab. Balangan',
      'Kota Banjarmasin',
      'Kota Banjarbaru',
      'Kab. Paser',
      'Kab. Kutai Kartanegara',
      'Kab. Berau',
      'Kab. Kutai Barat',
      'Kab. Kutai Timur',
      'Kab. Penajam Paser Utara',
      'Kab. Mahakam Ulu',
      'Kota Balikpapan',
      'Kota Samarinda',
      'Kota Bontang',
      'Kab. Bulungan',
      'Kab. Malinau',
      'Kab. Nunukan',
      'Kab. Tana Tidung',
      'Kota Tarakan',
      'Kab. Bolaang Mongondow',
      'Kab. Minahasa',
      'Kab. Kepulauan Sangihe',
      'Kab. Kepulauan Talaud',
      'Kab. Minahasa Selatan',
      'Kab. Minahasa Utara',
      'Kab. Minahasa Tenggara',
      'Kab. Bolaang Mongondow Utara',
      'Kab. Kep. Siau Tagulandang Biaro',
      'Kab. Bolaang Mongondow Timur',
      'Kab. Bolaang Mongondow Selatan',
      'Kota Manado',
      'Kota Bitung',
      'Kota Tomohon',
      'Kota Kotamobagu',
      'Kab. Banggai',
      'Kab. Poso',
      'Kab. Donggala',
      'Kab. Toli Toli',
      'Kab. Buol',
      'Kab. Morowali',
      'Kab. Banggai Kepulauan',
      'Kab. Parigi Moutong',
      'Kab. Tojo Una Una',
      'Kab. Sigi',
      'Kab. Banggai Laut',
      'Kab. Morowali Utara',
      'Kota Palu',
      'Kab. Kepulauan Selayar',
      'Kab. Bulukumba',
      'Kab. Bantaeng',
      'Kab. Jeneponto',
      'Kab. Takalar',
      'Kab. Gowa',
      'Kab. Sinjai',
      'Kab. Bone',
      'Kab. Maros',
      'Kab. Pangkajene Kepulauan',
      'Kab. Barru',
      'Kab. Soppeng',
      'Kab. Wajo',
      'Kab. Sidenreng Rappang',
      'Kab. Pinrang',
      'Kab. Enrekang',
      'Kab. Luwu',
      'Kab. Tana Toraja',
      'Kab. Polewali Mamasa',
      'Kab. Luwu Utara',
      'Kab. Luwu Timur',
      'Kab. Toraja Utara',
      'Kota Makassar',
      'Kota Pare Pare',
      'Kota Palopo',
      'Kab. Kolaka',
      'Kab. Konawe',
      'Kab. Muna',
      'Kab. Buton',
      'Kab. Konawe Selatan',
      'Kab. Bombana',
      'Kab. Wakatobi',
      'Kab. Kolaka Utara',
      'Kab. Konawe Utara',
      'Kab. Buton Utara',
      'Kab. Kolaka Timur',
      'Kab. Konawe Kepulauan',
      'Kab. Muna Barat',
      'Kab. Buton Tengah',
      'Kab. Buton Selatan',
      'Kota Kendari',
      'Kota Bau Bau',
      'Kab. Gorontalo',
      'Kab. Boalemo',
      'Kab. Bone Bolango',
      'Kab. Pohuwato',
      'Kab. Gorontalo Utara',
      'Kota Gorontalo',
      'Kab. Mamuju Utara',
      'Kab. Mamuju',
      'Kab. Mamasa',
      'Kab. Polewali Mandar',
      'Kab. Majene',
      'Kab. Mamuju Tengah',
      'Kab. Maluku Tengah',
      'Kab. Maluku Tenggara',
      'Kab Maluku Tenggara Barat',
      'Kab. Buru',
      'Kab. Seram Bagian Timur',
      'Kab. Seram Bagian Barat',
      'Kab. Kepulauan Aru',
      'Kab. Maluku Barat Daya',
      'Kab. Buru Selatan',
      'Kota Ambon',
      'Kota Tual',
      'Kab. Halmahera Barat',
      'Kab. Halmahera Tengah',
      'Kab. Halmahera Utara',
      'Kab. Halmahera Selatan',
      'Kab. Kepulauan Sula',
      'Kab. Halmahera Timur',
      'Kab. Pulau Morotai',
      'Kab. Pulau Taliabu',
      'Kota Ternate',
      'Kota Tidore Kepulauan',
      'Kab. Merauke',
      'Kab. Jayawijaya',
      'Kab. Jayapura',
      'Kab. Nabire',
      'Kab. Kepulauan Yapen',
      'Kab. Biak Numfor',
      'Kab. Puncak Jaya',
      'Kab. Paniai',
      'Kab. Mimika',
      'Kab. Sarmi',
      'Kab. Keerom',
      'Kab Pegunungan Bintang',
      'Kab. Yahukimo',
      'Kab. Tolikara',
      'Kab. Waropen',
      'Kab. Boven Digoel',
      'Kab. Mappi',
      'Kab. Asmat',
      'Kab. Supiori',
      'Kab. Mamberamo Raya',
      'Kab. Mamberamo Tengah',
      'Kab. Yalimo',
      'Kab. Lanny Jaya',
      'Kab. Nduga',
      'Kab. Puncak',
      'Kab. Dogiyai',
      'Kab. Intan Jaya',
      'Kab. Deiyai',
      'Kota Jayapura',
      'Kab. Sorong',
      'Kab. Manokwari',
      'Kab. Fak Fak',
      'Kab. Sorong Selatan',
      'Kab. Raja Ampat',
      'Kab. Teluk Bintuni',
      'Kab. Teluk Wondama',
      'Kab. Kaimana',
      'Kab. Tambrauw',
      'Kab. Maybrat',
      'Kab. Manokwari Selatan',
      'Kab. Pegunungan Arfak',
      'Kota Sorong'
    ];

    return Scaffold(
      // extendBodyBehindAppBar: true,
      // appBar: AppBar(
      //   backgroundColor: Colors.transparent,
      //   elevation: 0,
      //   title: Text(
      //     "Register",
      //     style: GoogleFonts.balooDa2(
      //         fontSize: 15,
      //         fontWeight: bold,
      //         color: Color.fromARGB(248, 255, 255, 255)),
      //   ),
      //   iconTheme: IconThemeData(color: Colors.white),
      // ),
      body: Stack(
        children: [
          Positioned.fill(
            child: Image.asset(
              'lib/Assets/Images/realbg_regis.png',
              fit: BoxFit.cover,
            ),
          ),
          ListView(
            children: [
              Container(
                alignment: Alignment.topLeft,
                padding: EdgeInsets.only(top: 60.0, left: 25.0),
                child: Row(
                  children: [
                    Text(
                      "Register",
                      style: GoogleFonts.balooDa2(
                        fontSize: 17,
                        fontWeight: FontWeight.bold,
                        color: Color.fromARGB(248, 253, 253, 253),
                      ),
                    ),
                  ],
                ),
              ),
              Container(
                alignment: Alignment.topRight,
                padding: EdgeInsets.only(top: 30, right: 25),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.end,
                  children: [
                    Text(
                      "Address Contact",
                      style: GoogleFonts.balooDa2(
                        fontSize: 12,
                        fontWeight: FontWeight.bold,
                        color: Color.fromARGB(248, 255, 255, 255),
                      ),
                    ),
                    SizedBox(height: 1),
                    Text(
                      "2 of 4",
                      style: GoogleFonts.balooDa2(
                        fontSize: 8,
                        color: Color.fromARGB(255, 168, 165, 165),
                      ),
                    ),
                  ],
                ),
              ),
              Align(
                alignment: Alignment.topLeft,
                child: Padding(
                  padding: const EdgeInsets.only(
                    top: 0.10,
                    left: 25,
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Container(
                        alignment: Alignment.centerLeft,
                        child: Text(
                          "Country",
                          style: GoogleFonts.balooDa2(
                            fontSize: 14,
                            fontWeight: FontWeight.bold,
                            color: Color.fromARGB(255, 255, 255, 255),
                          ),
                        ),
                      ),
                      SizedBox(height: 8),
                      Container(
                        width: 350,
                        child: DropdownButton<String>(
                          value: selectedCountry,
                          isExpanded: true,
                          onChanged: (String? newValue) {
                            if (newValue != null) {
                              setState(() {
                                selectedCountry = newValue;
                              });
                            }
                          },
                          items: country
                              .map<DropdownMenuItem<String>>((String value) {
                            return DropdownMenuItem<String>(
                              value: value,
                              child: Text(value),
                            );
                          }).toList(),
                          underline: Container(
                            height: 1,
                            color: Colors.grey,
                          ),
                          style: TextStyle(
                              color: const Color.fromARGB(255, 56, 56, 56),
                              fontSize: 14),
                          icon: Icon(Icons.arrow_drop_down),
                        ),
                      ),
                      SizedBox(height: 8),
                      Text(
                        "Province",
                        style: GoogleFonts.balooDa2(
                          fontSize: 14,
                          fontWeight: FontWeight.bold,
                          color: Color.fromARGB(255, 255, 255, 255),
                        ),
                      ),
                      SizedBox(height: 8),
                      Container(
                        width: 350,
                        child: DropdownButton<String>(
                          value: selectedProvince,
                          isExpanded: true,
                          onChanged: (String? newValue) {
                            if (newValue != null) {
                              setState(() {
                                selectedProvince = newValue;
                              });
                            }
                          },
                          items: province
                              .map<DropdownMenuItem<String>>((String value) {
                            return DropdownMenuItem<String>(
                              value: value,
                              child: Text(value),
                            );
                          }).toList(),
                          underline: Container(
                            height: 1,
                            color: Colors.grey,
                          ),
                          style: TextStyle(
                              color: const Color.fromARGB(255, 56, 56, 56),
                              fontSize: 14),
                          icon: Icon(Icons.arrow_drop_down),
                        ),
                      ),
                      SizedBox(height: 8),
                      Text(
                        "City",
                        style: GoogleFonts.balooDa2(
                          fontSize: 14,
                          fontWeight: FontWeight.bold,
                          color: Color.fromARGB(255, 255, 255, 255),
                        ),
                      ),
                      SizedBox(height: 8),
                      Container(
                        width: 350,
                        child: DropdownButton<String>(
                          value: selectedCity,
                          isExpanded: true,
                          onChanged: (String? newValue) {
                            if (newValue != null) {
                              setState(() {
                                selectedCity = newValue;
                              });
                            }
                          },
                          items: city
                              .map<DropdownMenuItem<String>>((String value) {
                            return DropdownMenuItem<String>(
                              value: value,
                              child: Text(value),
                            );
                          }).toList(),
                          underline: Container(
                            height: 1,
                            color: Colors.grey,
                          ),
                          style: TextStyle(
                              color: const Color.fromARGB(255, 56, 56, 56),
                              fontSize: 14),
                          icon: Icon(Icons.arrow_drop_down),
                        ),
                      ),
                      SizedBox(height: 8),
                      Text(
                        "Branch Officers",
                        style: GoogleFonts.balooDa2(
                          fontSize: 14,
                          fontWeight: FontWeight.bold,
                          color: Color.fromARGB(255, 255, 255, 255),
                        ),
                      ),
                      SizedBox(height: 8),
                      Container(
                        width: 350,
                        child: DropdownButton<String>(
                          value: selectedOfficer,
                          isExpanded: true,
                          onChanged: (String? newValue) {
                            if (newValue != null) {
                              setState(() {
                                selectedOfficer = newValue;
                              });
                            }
                          },
                          items: officer
                              .map<DropdownMenuItem<String>>((String value) {
                            return DropdownMenuItem<String>(
                              value: value,
                              child: Text(value),
                            );
                          }).toList(),
                          underline: Container(
                            height: 1,
                            color: Colors.grey,
                          ),
                          style: TextStyle(
                              color: const Color.fromARGB(255, 56, 56, 56),
                              fontSize: 14),
                          icon: Icon(Icons.arrow_drop_down),
                        ),
                      ),
                      SizedBox(height: 8),
                      Text(
                        "Resindence Address",
                        style: GoogleFonts.balooDa2(
                          fontSize: 14,
                          fontWeight: FontWeight.bold,
                          color: Color.fromARGB(255, 255, 255, 255),
                        ),
                      ),
                      SizedBox(height: 8),
                      Container(
                        width: 350,
                        child: TextField(
                          decoration: InputDecoration(
                            border: OutlineInputBorder(),
                            hintText: 'Input Your Resindence Address',
                          ),
                        ),
                      ),
                      SizedBox(height: 8),
                      Text(
                        "Job Type",
                        style: GoogleFonts.balooDa2(
                          fontSize: 14,
                          fontWeight: FontWeight.bold,
                          color: Color.fromARGB(255, 255, 255, 255),
                        ),
                      ),
                      SizedBox(height: 8),
                      Container(
                        width: 350,
                        child: TextField(
                          decoration: InputDecoration(
                            border: OutlineInputBorder(),
                            hintText: 'Select Job Type',
                            contentPadding: EdgeInsets.symmetric(
                              vertical: 3,
                              horizontal: 10,
                            ),
                          ),
                        ),
                      ),
                      SizedBox(height: 8),
                      Text(
                        "Bussiness Field",
                        style: GoogleFonts.balooDa2(
                          fontSize: 14,
                          fontWeight: FontWeight.bold,
                          color: Color.fromARGB(255, 255, 255, 255),
                        ),
                      ),
                      SizedBox(height: 8),
                      Container(
                        width: 350,
                        child: TextField(
                          decoration: InputDecoration(
                            border: OutlineInputBorder(),
                            hintText: 'Select Bussiness Field',
                            contentPadding: EdgeInsets.symmetric(
                              vertical: 3,
                              horizontal: 10,
                            ),
                          ),
                        ),
                      ),
                      SizedBox(height: 8),
                      Text(
                        "Company Name",
                        style: GoogleFonts.balooDa2(
                          fontSize: 14,
                          fontWeight: FontWeight.bold,
                          color: Color.fromARGB(255, 255, 255, 255),
                        ),
                      ),
                      SizedBox(height: 8),
                      Container(
                        width: 350,
                        child: TextField(
                          decoration: InputDecoration(
                            border: OutlineInputBorder(),
                            hintText: 'Input Your Company Name',
                            contentPadding: EdgeInsets.symmetric(
                              vertical: 3,
                              horizontal: 10,
                            ),
                          ),
                        ),
                      ),
                      SizedBox(
                        height: 20,
                      ),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.start,
                        children: [
                          Padding(
                            padding: EdgeInsets.only(left: 2.0),
                          ),
                          ElevatedButton(
                            onPressed: () {
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (context) => RegisPage()),
                              );
                            },
                            child: Text("Back"),
                            style: ElevatedButton.styleFrom(
                              backgroundColor:
                                  Color.fromARGB(255, 228, 228, 228),
                              foregroundColor: Color.fromARGB(248, 9, 9, 9),
                              minimumSize: Size(100, 40),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(10),
                              ),
                            ),
                          ),
                          SizedBox(
                            width: 147,
                          ),
                          ElevatedButton(
                            onPressed: () {
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (context) => Regis3Page()),
                              );
                            },
                            child: Text("Next"),
                            style: ElevatedButton.styleFrom(
                              backgroundColor:
                                  Color.fromARGB(123, 123, 111, 111),
                              foregroundColor: Color.fromARGB(248, 9, 9, 9),
                              minimumSize: Size(100, 40),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(10),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
